# Generated by Django 3.2.7 on 2021-11-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posts', '0002_auto_20211111_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_requirements',
            name='requirements',
            field=models.TextField(),
        ),
    ]
