# Generated by Django 3.2.7 on 2021-11-16 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_posts', '0004_auto_20211116_0249'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='job_postings',
            new_name='Job_postingss',
        ),
    ]
