# Generated by Django 3.2.7 on 2021-11-16 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posts', '0005_rename_job_postings_job_postingss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_postingss',
            name='requirements',
            field=models.TextField(),
        ),
    ]
