# Generated by Django 3.2.7 on 2021-11-16 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_posts', '0006_alter_job_postingss_requirements'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job_postingss',
            new_name='Job_postings',
        ),
    ]
