# Generated by Django 3.2.7 on 2021-11-16 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_posts', '0007_rename_job_postingss_job_postings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job_postings',
            new_name='Job_posting',
        ),
    ]
