# Generated by Django 3.2.7 on 2021-11-16 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_posts', '0008_rename_job_postings_job_posting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job_posting',
            new_name='Job_postings',
        ),
    ]
